- name: play level variables
  hosts: local
  connection: local
  vars_files:
   - course.yaml 
  tasks:
   - name: print variables
     ansible.builtin.debug:
       msg: "course is: {{COURSE}}, Trainer is: {{TRAINER}}, and the duration is: {{DURATION}}"
